# Generated by Django 5.0.3 on 2024-04-12 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_addres_area_alter_addres_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addres',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userAddress', to=settings.AUTH_USER_MODEL),
        ),
    ]
