# Generated by Django 4.0.3 on 2024-03-26 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0012_alter_reviewitem_item_alter_reviewitem_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystore.storeitem'),
        ),
    ]
