# Generated by Django 4.0.3 on 2024-03-27 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0018_alter_reviewitem_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='itemImages/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystore.storeitem')),
            ],
        ),
    ]
