# Generated by Django 4.0.3 on 2024-03-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0019_storeitemimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoreItemImage',
            new_name='ItemImage',
        ),
    ]
