# Generated by Django 4.0.3 on 2024-03-27 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0020_rename_storeitemimage_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='standard',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='type',
            field=models.CharField(blank=True, choices=[('Syllabus', 'Syllabus'), ('Single book', 'Single book'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
