# Generated by Django 4.0.3 on 2024-03-28 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0023_storeitem_description_alter_storeitem_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeitem',
            old_name='description',
            new_name='storeDesc',
        ),
    ]
