# Generated by Django 4.0.3 on 2024-03-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0025_rename_storedesc_storeitem_itemdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='img',
            field=models.ImageField(upload_to='storeImages/'),
        ),
    ]
