# Generated by Django 5.0.3 on 2024-04-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0029_storeitem_topay'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystore',
            name='recharge',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
