# Generated by Django 5.0.3 on 2024-04-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0030_mystore_recharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to='storeImages/'),
        ),
    ]
