# Generated by Django 5.0.3 on 2024-04-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0034_alter_mystore_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitem',
            name='freeze_date',
        ),
        migrations.RemoveField(
            model_name='storeitem',
            name='frozen',
        ),
        migrations.AddField(
            model_name='storeitem',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
