# Generated by Django 5.0.3 on 2024-04-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0041_alter_reviewitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mystore',
            name='status',
        ),
    ]
