# Generated by Django 5.0.3 on 2024-04-03 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_cart_alter_cartitem_item'),
        ('mystore', '0028_alter_itemimage_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_store', to='mystore.mystore'),
        ),
    ]
